//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseManagerArek.WinFormsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Position { get; set; }
        public decimal Salary { get; set; }
        public System.DateTime EmploymentDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneMobile { get; set; }
        public string PhoneOffice { get; set; }
        public string Mail { get; set; }
        public int Id { get; set; }
    }
}
